version: "3.9"

networks:
  tech-net:
    external: true
    name: tech-net

services:
  mysql:
    image: mysql
    container_name: ms-schedule-db
    env_file:
      - .env.mysql
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql_init.sql:ro
    networks:
      - tech-net

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms-schedule
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - tech-net