POST {{BASE_URL}}/auth
Content-Type: application/json

{
    "email": "nurse1@example.com",
    "password": "123456"
}

> {%
    client.global.set("token", response.body.token)
%}

###

PATCH {{BASE_URL}}/consultation/update-status/5
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "CANCELED"
}
