POST {{ BASE_URL }}/auth
Content-Type: application/json

{
  "email": "nurse1@example.com",
  "password": "123456"
}

> {%
    client.global.set("token", response.body.token)
%}

###

POST {{BASE_URL}}/consultation
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nurseId": 1,
  "doctorId": 2,
  "patientId": 1,
  "dateTime": "2025-10-05T14:30:00",
  "reason": "Dor de barriga"
}
