POST {{ BASE_URL }}/auth
Content-Type: application/json

{
  "email": "nurse1@example.com",
  "password": "123456"
}

> {%
    client.global.set("token", response.body.token)
%}

###

GET {{BASE_URL}}/auth/token-validator
Accept: application/json
Authorization: Bearer {{ token }}

###